name: resource_manager
services:
  mysql:
    image: "mysql:latest"
    environment:
        - MYSQL_DATABASE=test
        - MYSQL_ROOT_PASSWORD=heslo
        - MYSQL_USER=user
        - MYSQL_PASSWORD=heslo
    ports:
        - "3307:3306"
    networks:
        - rm_net
  api:
    build: .
    ports:
      - "8000:5000"
    stdin_open: true 
    tty: true
    depends_on:
      mysql:
        condition: service_started
    networks:
        - rm_net
        
networks:
  rm_net:
    name: rm_net
